name: mongodb
services:
  mongodb:
    cpu_shares: 10
    command: []
    deploy:
      resources:
        limits:
          memory: 256M
    environment:
      - MONGO_INITDB_DATABASE=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_ROOT_USERNAME=root
    image: webhippie/mongodb:4.0-arm64
    ports:
      - mode: ingress
        target: 27017
        published: "27017"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /home/docker/mongodb/mongo/database
        target: /data/db
        bind:
          create_host_path: true
      - type: bind
        source: /home/docker/mongodb/mongo/init-mongo.js
        target: /docker-entrypoint-initdb.d/init-mongo.js
        read_only: true
        bind:
          create_host_path: true
    devices: []
    cap_add: []
    networks:
      - default
    privileged: false
    container_name: ""
    hostname: ""
networks:
  default:
    name: mongodb_default
x-casaos:
  author: self
  category: self
  hostname: ""
  icon: https://img.icons8.com/?size=64&id=8rKdRqZFLurS&format=png
  index: /
  port_map: "27017"
  scheme: http
  title:
    custom: Mongo DB
