version: '3.9'
services:
    elasticsearch:
        image: 'docker.elastic.co/elasticsearch/elasticsearch:8.12.0-arm64'
        environment:
            - xpack.ml.enabled=false
            - discovery.type=single-node
        ports:
            - '9300:9300'
            - '9200:9200'
