global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: "prometheus"
    tls_config:
      insecure_skip_verify: true
    scrape_interval: 5s
    static_configs:
      - targets: ["juhdi.lan:9092"]

  - job_name: mysql # To get metrics about the mysql exporter’s targets
    params:
      # Not required. Will match value to child in config file. Default value is `client`.
      auth_module: [client.servers]
    static_configs:
      - targets:
        # All mysql hostnames or unix sockets to monitor.
        - ${mysql_address}:${mysql_port}
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        # The mysqld_exporter host:port
        replacement: juhdi.lan:9104

  - job_name: traefik
    static_configs:
      - targets: ['juhdi.lan:8088']

  # - job_name: "snmp"
  #   static_configs:
  #     - targets:
  #         - 192.168.88.1 # SNMP Device 3
  #   metrics_path: /snmp
  #   params:
  #     module: [mikrotik]
  #   relabel_configs:
  #     - source_labels: [__address__]
  #       target_label: __param_target
  #     - source_labels: [__param_target]
  #       target_label: instance
  #     - target_label: __address__
  #       replacement: 192.168.88.10:9116 # The SNMP exporter's real hostname:port.
