version: '3.8'
services:
  cache:
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
    volumes: 
      - cache:/data
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    # environment:
    #   - REDIS_PASSWORD=my-password
    #   - REDIS_PORT=6379
    #   - REDIS_DATABASES=11
volumes:
  cache:
    driver: local

x-casaos:
  hostname: ""
  scheme: http
  index: /
  port_map: "6379"
  author: self
  category: self
  icon: "https://img.icons8.com/?size=64&id=pHS3eRpynIRQ&format=png"
  title:
    custom: Redis
